import pygame
CELL=30
BOARD_WIDTH= 10*CELL
BOARD_HEIGHT=20*CELL
PADDING=30
NEXT_PIECE_BAR=200
SCORE_BOX=200
HOLD_BOX=200
WINDOW_WIDTH=BOARD_WIDTH+3*PADDING + NEXT_PIECE_BAR+HOLD_BOX
WINDOW_HEIGHT=BOARD_HEIGHT + 2*PADDING
